# Generic code template + worked example (in -> out) per leaf anchor. No file IO.
CODE={
'gl-leaf-where':"SELECT entity, MIN(val) AS best\nFROM tbl\nWHERE qualifies          -- drop non-qualifiers entirely\nGROUP BY entity;",
'gl-leaf-rownumber':"WITH ranked AS (\n  SELECT *, ROW_NUMBER() OVER (PARTITION BY entity ORDER BY val) AS rn\n  FROM tbl\n)\nSELECT entity,\n       CASE WHEN qualifies THEN name END AS winner_name  -- blank if not\nFROM ranked WHERE rn = 1;",
'gl-leaf-distincton':"-- Postgres only\nSELECT DISTINCT ON (entity) entity, name, val\nFROM tbl\nORDER BY entity, val;        -- keeps the top row per entity",
'gl-leaf-case':"SELECT e.entity,\n       CASE WHEN e.qualifies THEN MIN(t.val) END AS best  -- NULL if not\nFROM entities e\nLEFT JOIN tbl t ON t.entity = e.entity\nGROUP BY e.entity, e.qualifies;",
'gl-leaf-onclause':"SELECT e.entity, COUNT(t.id) AS cnt\nFROM entities e\nLEFT JOIN tbl t\n  ON t.entity = e.entity\n AND t.flag             -- gate which rows count; every entity stays\nGROUP BY e.entity;",
'gl-case-around-threshold':"SELECT a.entity,\n       CASE WHEN a.score >= 70           -- number gate on table A\n            THEN MIN(b.val) END AS best  -- NULL when the number misses\nFROM entity a\nLEFT JOIN fact b ON b.entity = a.entity\nGROUP BY a.entity, a.score;",
'gl-case-around-flag':"SELECT a.entity,\n       CASE WHEN a.is_active             -- yes/no flag on table A\n            THEN MAX(b.val) END AS best  -- NULL when the flag is off\nFROM entity a\nLEFT JOIN fact b ON b.entity = a.entity\nGROUP BY a.entity, a.is_active;",
'gl-case-inside':"SELECT a.entity,\n       SUM(CASE WHEN b.price > 75 THEN 1 ELSE 0 END) AS hits  -- count only qualifying rows\nFROM entity a\nLEFT JOIN fact b ON b.entity = a.entity   -- keeps every entity; non-matches add 0\nGROUP BY a.entity;",
'dd-leaf-rownumber':"WITH d AS (\n  SELECT *, ROW_NUMBER() OVER (PARTITION BY key ORDER BY created_at DESC) AS rn\n  FROM tbl\n)\nDELETE FROM tbl WHERE id IN (SELECT id FROM d WHERE rn > 1);",
'dd-leaf-selfjoin':"DELETE FROM tbl a\nUSING tbl b\nWHERE a.key = b.key\n  AND a.id > b.id;        -- the higher-id twin loses",
'dd-leaf-minid':"DELETE FROM tbl\nWHERE id NOT IN (SELECT MIN(id) FROM tbl GROUP BY key);",
'pit-leaf-fill':"SELECT d.day, e.entity,\n  (SELECT val FROM hist h\n   WHERE h.entity = e.entity AND h.ts <= d.day\n   ORDER BY h.ts DESC LIMIT 1) AS val_as_of\nFROM calendar d CROSS JOIN entities e;",
'pit-leaf-default':"SELECT e.entity, COALESCE(h.val, 0) AS val_as_of   -- default if none\nFROM entities e\nLEFT JOIN LATERAL (\n  SELECT val FROM hist\n  WHERE entity = e.entity AND ts <= DATE '2024-01-01'\n  ORDER BY ts DESC LIMIT 1\n) h ON true;",
'pit-leaf-asof':"SELECT DISTINCT ON (entity) entity, val\nFROM hist\nWHERE ts <= DATE '2024-01-01'   -- the cutoff\nORDER BY entity, ts DESC;",
'up-leaf-aggregate':"WITH long AS (\n  SELECT id, 'q1' AS period, q1 AS amt FROM tbl\n  UNION ALL SELECT id, 'q2', q2 FROM tbl\n)\nSELECT period, SUM(amt) FROM long GROUP BY period;",
'up-leaf-keep':"SELECT id, 'q1' AS period, q1 AS amt FROM tbl\nUNION ALL\nSELECT id, 'q2', q2 FROM tbl;     -- NULL cells stay as rows",
'up-leaf-drop':"SELECT * FROM (\n  SELECT id, 'q1' AS period, q1 AS amt FROM tbl\n  UNION ALL SELECT id, 'q2', q2 FROM tbl\n) u\nWHERE amt IS NOT NULL;             -- drop the blanks",
'ej-leaf-selfjoin':"SELECT e.name AS employee, m.name AS manager\nFROM emp e\nJOIN emp m ON e.manager_id = m.id;",
'ej-leaf-cross':"SELECT e.entity, d.day, COALESCE(a.val, 0) AS val\nFROM entities e\nCROSS JOIN calendar d\nLEFT JOIN actuals a ON a.entity = e.entity AND a.day = d.day;",
'ej-leaf-pergroup':"SELECT t.*, g.grp_avg\nFROM tbl t\nJOIN (SELECT key, AVG(val) AS grp_avg FROM tbl GROUP BY key) g\n  ON g.key = t.key;",
'ej-leaf-compound':"-- threshold AND never did B recently, still counting ALL of B\nSELECT m.id, m.balance, COUNT(c.dt) AS total   -- LEFT JOIN counts every B row\nFROM master m\nLEFT JOIN child c ON c.id = m.id              -- no date here\nWHERE m.balance >= 500\n  AND NOT EXISTS (                            -- anti-join: drop anyone active recently\n    SELECT 1 FROM child x\n    WHERE x.id = m.id AND x.dt >= DATE '2024-10-01')\nGROUP BY m.id, m.balance;",
'ej-leaf-lookup':"SELECT t.id, d.label\nFROM tbl t\nJOIN dim d ON d.id = t.dim_id;",
'sc-leaf-aggregate':"SELECT MAX(val) AS top_val FROM tbl;",
'sc-leaf-ratio':"SELECT 1.0 * COUNT(*) FILTER (WHERE flag) / COUNT(*) AS rate\nFROM tbl;",
'sc-leaf-nth':"SELECT DISTINCT val\nFROM tbl\nORDER BY val DESC\nOFFSET 1 LIMIT 1;        -- 2nd highest = OFFSET N-1",
'sc-leaf-top1':"SELECT *\nFROM tbl\nORDER BY val DESC\nLIMIT 1;",
'rp-multi-special':"-- e.g. rank delta between periods\nSELECT key, period, val,\n  val - LAG(val) OVER (PARTITION BY key ORDER BY period) AS delta\nFROM tbl;",
'rp-multi-topn':"WITH r AS (\n  SELECT *, ROW_NUMBER() OVER (PARTITION BY grp ORDER BY val DESC) AS rn\n  FROM tbl\n)\nSELECT * FROM r WHERE rn <= 2;     -- top N per group",
'rp-multi-nth':"WITH r AS (\n  SELECT *, ROW_NUMBER() OVER (PARTITION BY grp ORDER BY val DESC) AS rn\n  FROM tbl\n)\nSELECT * FROM r WHERE rn = 2;      -- exactly the Nth",
'rp-multi-top1-by-date':"SELECT DISTINCT ON (grp) grp, val\nFROM tbl\nORDER BY grp, ts DESC;            -- most recent per group",
'rp-multi-top1-by-value':"WITH r AS (\n  SELECT *, ROW_NUMBER() OVER (PARTITION BY grp ORDER BY val DESC) AS rn\n  FROM tbl\n)\nSELECT * FROM r WHERE rn = 1;",
'rf-leaf-pattern':"SELECT * FROM tbl WHERE name LIKE 'A%';",
'rf-leaf-null':"SELECT * FROM tbl WHERE val IS NULL;",
'rf-leaf-membership':"SELECT * FROM tbl\nWHERE id IN (SELECT id FROM other);",
'rf-leaf-antijoin':"SELECT t.* FROM tbl t\nLEFT JOIN other o ON o.id = t.id\nWHERE o.id IS NULL;               -- never matched",
'rf-leaf-having':"SELECT key FROM tbl\nGROUP BY key\nHAVING COUNT(*) >= 3;",
'rf-leaf-compare':"SELECT * FROM tbl\nWHERE val BETWEEN 10 AND 20 AND status = 'active';",
'ag-leaf-having':"SELECT key, SUM(val) AS total\nFROM tbl GROUP BY key\nHAVING SUM(val) > 100;",
'ag-leaf-conditional':"SELECT key,\n  SUM(CASE WHEN type = 'a' THEN val END) AS a_total,\n  SUM(CASE WHEN type = 'b' THEN val END) AS b_total\nFROM tbl GROUP BY key;",
'ag-leaf-ratio':"SELECT key,\n  1.0 * COUNT(*) FILTER (WHERE flag) / COUNT(*) AS rate\nFROM tbl GROUP BY key;",
'ag-leaf-countdistinct':"SELECT key, COUNT(DISTINCT user_id) AS users\nFROM tbl GROUP BY key;",
'ag-leaf-count':"SELECT key, COUNT(*) AS n FROM tbl GROUP BY key;",
'ag-leaf-sumavg':"SELECT key, SUM(val) AS total, AVG(val) AS mean\nFROM tbl GROUP BY key;",
'rp-leaf-median':"SELECT key,\n  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY val) AS median\nFROM tbl GROUP BY key;",
'rp-leaf-pct-agg':"SELECT key,\n  PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY val) AS p90\nFROM tbl GROUP BY key;",
'rp-leaf-pctrank':"WITH r AS (\n  SELECT *, PERCENT_RANK() OVER (PARTITION BY key ORDER BY val DESC) AS pr\n  FROM tbl\n)\nSELECT * FROM r WHERE pr <= 0.10;   -- top 10%",
'rp-leaf-ntile':"SELECT *, NTILE(4) OVER (ORDER BY val) AS quartile\nFROM tbl;",
'rp-leaf-rownum':"WITH r AS (\n  SELECT *, ROW_NUMBER() OVER (PARTITION BY key ORDER BY val DESC) AS rn\n  FROM tbl\n)\nSELECT * FROM r WHERE rn <= 2;",
'rp-leaf-rank':"WITH r AS (\n  SELECT *, RANK() OVER (ORDER BY val DESC) AS rk\n  FROM tbl\n)\nSELECT * FROM r WHERE rk = 3;       -- ranks skip after ties",
'rp-leaf-denserank':"WITH r AS (\n  SELECT *, DENSE_RANK() OVER (ORDER BY val DESC) AS rk\n  FROM tbl\n)\nSELECT * FROM r WHERE rk = 2;       -- no gaps after ties",
'un-leaf-labels':"WITH labels(name) AS (VALUES ('a'),('b'),('c'))\nSELECT l.name, COUNT(t.id) AS n\nFROM labels l\nLEFT JOIN tbl t ON t.name = l.name\nGROUP BY l.name;",
'un-leaf-reconcile':"SELECT id, 'only in A' AS src FROM a WHERE id NOT IN (SELECT id FROM b)\nUNION ALL\nSELECT id, 'only in B'        FROM b WHERE id NOT IN (SELECT id FROM a);",
'un-leaf-stack':"SELECT 'new' AS metric, COUNT(*) FROM users WHERE is_new\nUNION ALL\nSELECT 'churned',        COUNT(*) FROM users WHERE churned;",
'tx-leaf-update':"UPDATE tbl SET status = 'done' WHERE id = 1;",
'tx-leaf-coalesce':"SELECT COALESCE(nickname, name, 'n/a') AS display FROM tbl;",
'tx-leaf-case':"SELECT val,\n  CASE WHEN val >= 90 THEN 'A'\n       WHEN val >= 80 THEN 'B'\n       ELSE 'C' END AS grade\nFROM tbl;",
'tx-leaf-concat':"SELECT first || ' ' || last AS full_name FROM tbl;",
'tx-leaf-substring':"SELECT LEFT(code, 3) AS prefix,\n       SUBSTRING(code FROM 4) AS rest\nFROM tbl;",
'tx-leaf-upperlower':"SELECT UPPER(code) AS code_up, LOWER(email) AS email_lc FROM tbl;",
'tx-leaf-replace':"SELECT TRIM(REPLACE(phone, '-', '')) AS clean FROM tbl;",
'sess-start':"WITH flagged AS (\n  SELECT *,\n    CASE WHEN ts - LAG(ts) OVER (PARTITION BY user_id ORDER BY ts)\n              > INTERVAL '30 min' THEN 1 ELSE 0 END AS new_sess\n  FROM events\n)\nSELECT *,\n  SUM(new_sess) OVER (PARTITION BY user_id ORDER BY ts) AS session_id\nFROM flagged;",
'tw-tmpl-laglead':"SELECT *,\n  LAG(val)  OVER (PARTITION BY key ORDER BY t) AS prev,\n  LEAD(val) OVER (PARTITION BY key ORDER BY t) AS next\nFROM tbl;",
'tw-tmpl-firstlast':"SELECT *,\n  FIRST_VALUE(val) OVER (PARTITION BY key ORDER BY t\n    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS first_val\nFROM tbl;",
'tw-tmpl-pit':"SELECT DISTINCT ON (entity) entity, val\nFROM hist\nWHERE ts <= DATE '2024-01-01'\nORDER BY entity, ts DESC;",
'tw-tmpl-sliding':"SELECT *,\n  AVG(val) OVER (PARTITION BY key ORDER BY t\n    ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS rolling\nFROM tbl;",
'tw-tmpl-benchmark':"SELECT *,\n  val - AVG(val) OVER (PARTITION BY key) AS vs_group_avg\nFROM tbl;",
'tw-tmpl-running':"SELECT *,\n  SUM(val) OVER (PARTITION BY key ORDER BY t) AS running_total\nFROM tbl;",
'tw-tmpl-benchmark-frame':"SELECT *,\n  AVG(val) OVER (PARTITION BY key ORDER BY t\n    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS group_avg\nFROM tbl;",
'nb-leaf-matchup':"SELECT player, SUM(score) AS pts FROM (\n  SELECT home AS player, home_score AS score FROM games\n  UNION ALL SELECT away, away_score FROM games\n) s GROUP BY player;",
'nb-leaf-canon':"SELECT LEAST(a, b) AS p1, GREATEST(a, b) AS p2, COUNT(*)\nFROM pairs GROUP BY 1, 2;",
'nb-leaf-pool':"SELECT id, COUNT(*) FROM (\n  SELECT a AS id FROM pairs UNION ALL SELECT b FROM pairs\n) s GROUP BY id;",
'ea-leaf-leftjoin-on':"SELECT e.entity, COUNT(t.id) AS n\nFROM entities e\nLEFT JOIN tbl t ON t.entity = e.entity AND t.flag\nGROUP BY e.entity;",
'ea-leaf-membership':"SELECT entity FROM tbl\nGROUP BY entity\nHAVING MAX(CASE WHEN item='X' THEN 1 ELSE 0 END) = 1\n   AND MAX(CASE WHEN item='Z' THEN 1 ELSE 0 END) = 0;",
'ea-leaf-datewin':"SELECT u.id, COUNT(o.id) AS orders_30d\nFROM users u\nLEFT JOIN orders o\n  ON o.user_id = u.id\n AND o.ts >= u.signup AND o.ts < u.signup + INTERVAL '30 day'\nGROUP BY u.id;",
'ea-leaf-rate':"SELECT key,\n  1.0 * COUNT(*) FILTER (WHERE converted) / COUNT(*) AS conv_rate\nFROM tbl GROUP BY key;",
'ea-leaf-filter':"SELECT key, SUM(val) AS total\nFROM tbl GROUP BY key\nHAVING SUM(val) > 100;",
'ea-leaf-count':"SELECT e.entity, COUNT(t.id) AS n\nFROM entities e LEFT JOIN tbl t ON t.entity = e.entity\nGROUP BY e.entity;",
'ea-leaf-sumavg':"SELECT e.entity, SUM(t.val) AS total\nFROM entities e LEFT JOIN tbl t ON t.entity = e.entity\nGROUP BY e.entity;",
'ml-tmpl-310':"SELECT team,\n  SUM(CASE WHEN gf > ga THEN 3\n           WHEN gf = ga THEN 1 ELSE 0 END) AS pts\nFROM matches GROUP BY team;",
'ml-tmpl-winloss':"SELECT team,\n  COUNT(*) FILTER (WHERE gf > ga) AS wins,\n  COUNT(*) FILTER (WHERE gf < ga) AS losses\nFROM matches GROUP BY team;",
'ml-tmpl-gfga':"SELECT team, SUM(gf) AS goals_for, SUM(ga) AS goals_against,\n       SUM(gf) - SUM(ga) AS diff\nFROM matches GROUP BY team;",
'ml-tmpl-sumcol':"SELECT team, SUM(points) AS total FROM matches GROUP BY team;",
'pv-leaf-signed':"SELECT account,\n  SUM(CASE WHEN type = 'credit' THEN amt ELSE -amt END) AS net\nFROM ledger GROUP BY account;",
'pv-leaf-membership':"SELECT user_id FROM purchases\nGROUP BY user_id\nHAVING MAX(CASE WHEN item='X' THEN 1 ELSE 0 END) = 1\n   AND MAX(CASE WHEN item='Z' THEN 1 ELSE 0 END) = 0;",
'pv-leaf-threshold':"SELECT user_id FROM tbl\nGROUP BY user_id\nHAVING SUM(CASE WHEN cat='a' THEN amt ELSE 0 END) >= 50\n   AND SUM(CASE WHEN cat='b' THEN amt ELSE 0 END) >= 50;",
'pv-leaf-derived':"SELECT user_id,\n  COUNT(*) FILTER (WHERE EXTRACT(dow FROM ts) = 0) AS sun,\n  COUNT(*) FILTER (WHERE EXTRACT(dow FROM ts) = 6) AS sat\nFROM tbl GROUP BY user_id;",
'pv-leaf-zerofill':"SELECT user_id,\n  COALESCE(SUM(CASE WHEN cat='a' THEN amt END), 0) AS a,\n  COALESCE(SUM(CASE WHEN cat='b' THEN amt END), 0) AS b\nFROM tbl GROUP BY user_id;",
'pv-leaf-stored':"SELECT user_id,\n  SUM(CASE WHEN cat='a' THEN amt END) AS a,\n  SUM(CASE WHEN cat='b' THEN amt END) AS b\nFROM tbl GROUP BY user_id;",
'sg-leaf-overlap':"SELECT p.period, COUNT(*) AS active\nFROM periods p\nJOIN spans s ON s.start <= p.hi AND s.end >= p.lo\nGROUP BY p.period;",
'sg-leaf-lateral':"SELECT s.id, d.day\nFROM spans s\nCROSS JOIN LATERAL generate_series(s.start, s.end, INTERVAL '1 day') AS d(day);",
'sg-leaf-labels':"WITH tiers(label, lo, hi) AS (\n  VALUES ('low',0,9), ('mid',10,99)\n)\nSELECT t.label, COUNT(x.id)\nFROM tiers t LEFT JOIN tbl x ON x.val BETWEEN t.lo AND t.hi\nGROUP BY t.label;",
'sg-leaf-filtered':"SELECT d.day, e.entity, COUNT(a.id)\nFROM calendar d\nCROSS JOIN (SELECT DISTINCT entity FROM actuals) e\nLEFT JOIN actuals a ON a.entity = e.entity AND a.day = d.day\nGROUP BY d.day, e.entity;",
'sg-leaf-databounds':"WITH bounds AS (SELECT MIN(day) lo, MAX(day) hi FROM actuals)\nSELECT d.day\nFROM bounds b,\n     generate_series(b.lo, b.hi, INTERVAL '1 day') AS d(day);",
'sg-leaf-fullrange':"SELECT d.day, e.entity\nFROM generate_series(DATE '2024-01-01', DATE '2024-01-02',\n                     INTERVAL '1 day') AS d(day)\nCROSS JOIN entities e;",
'function-wrapped-scalar':"CREATE FUNCTION best_rate(p_id int) RETURNS numeric AS $$\n  SELECT 1.0 * SUM(x) / COUNT(*) FROM tbl WHERE id = p_id;\n$$ LANGUAGE sql;",
'function-wrapped':"CREATE FUNCTION top_rows(p_key int)\nRETURNS TABLE(id int, val numeric) AS $$\n  SELECT id, val FROM tbl WHERE key = p_key ORDER BY val DESC LIMIT 10;\n$$ LANGUAGE sql;",
'rc-leaf-neighbor-value':"SELECT *,\n  CASE WHEN val > LAG(val) OVER (PARTITION BY k ORDER BY t)\n       THEN 'up' END AS dir\nFROM tbl;",
'rc-leaf-gap-delta':"SELECT *,\n  t - LAG(t) OVER (PARTITION BY k ORDER BY t) AS gap\nFROM tbl;",
'rc-leaf-fixed-run':"SELECT * FROM tbl\nWHERE val = LAG(val)  OVER (ORDER BY id)\n  AND val = LEAD(val) OVER (ORDER BY id);",
'rc-leaf-pair-role':"SELECT key,\n  MAX(CASE WHEN role='end'   THEN t END)\n  - MAX(CASE WHEN role='start' THEN t END) AS duration\nFROM tbl GROUP BY key;",
'gi-leaf-int':"SELECT key, MIN(id), MAX(id)\nFROM (\n  SELECT *, id - ROW_NUMBER() OVER (ORDER BY id) AS grp FROM tbl\n) s GROUP BY key, grp;",
'gi-leaf-entity':"SELECT entity, status, MIN(day), MAX(day)\nFROM (\n  SELECT *,\n    ROW_NUMBER() OVER (PARTITION BY entity ORDER BY day)\n    - ROW_NUMBER() OVER (PARTITION BY entity, status ORDER BY day) AS grp\n  FROM tbl\n) s GROUP BY entity, status, grp;",
'gi-leaf-date-nogap':"SELECT MIN(day), MAX(day)\nFROM (\n  SELECT *, (day - ROW_NUMBER() OVER (ORDER BY day))::int AS grp FROM tbl\n) s GROUP BY grp;",
'gi-leaf-date-gap':"SELECT status, MIN(day), MAX(day)\nFROM (\n  SELECT *,\n    ROW_NUMBER() OVER (ORDER BY day)\n    - ROW_NUMBER() OVER (PARTITION BY status ORDER BY day) AS grp\n  FROM tbl\n) s GROUP BY status, grp;",
'ea-leaf-leftjoin-on':"SELECT d.dept, COUNT(o.id) AS q1_count\nFROM depts d\nLEFT JOIN orders o\n  ON o.dept = d.dept\n AND o.order_date >= DATE '2024-01-01'\n AND o.order_date <  DATE '2024-04-01'   -- date window in ON\nGROUP BY d.dept;",
'fj-leaf-status':"SELECT tm.team, COUNT(t.id) AS resolved\nFROM teams tm\nLEFT JOIN tickets t\n  ON t.team = tm.team AND t.status = 'resolved'   -- status in ON\nGROUP BY tm.team;",
'fj-leaf-threshold':"SELECT s.store, COUNT(o.id) AS big\nFROM stores s\nLEFT JOIN orders o\n  ON o.store = s.store AND o.amount >= 100   -- threshold in ON\nGROUP BY s.store;",
'fj-leaf-bothsides':"SELECT e.emp, COUNT(s.id) AS q1\nFROM emp e\nLEFT JOIN sess s\n  ON s.emp = e.emp\n AND s.d >= DATE '2024-01-01' AND s.d < DATE '2024-04-01'   -- right -> ON\nWHERE e.hire >= DATE '2024-01-01' AND e.hire < DATE '2025-01-01' -- left -> WHERE\nGROUP BY e.emp;",
'fj-leaf-sumcoalesce':"SELECT c.cust, COALESCE(SUM(o.amt), 0) AS spend\nFROM cust c\nLEFT JOIN orders o\n  ON o.cust = c.cust AND o.status = 'completed'   -- status in ON\nGROUP BY c.cust;",
'fj-leaf-existence':"SELECT u.usr,\n  CASE WHEN COUNT(o.id) > 0 THEN 1 ELSE 0 END AS ordered_2024\nFROM users u\nLEFT JOIN orders o\n  ON o.usr = u.usr\n AND o.order_date >= DATE '2024-01-01'\n AND o.order_date <  DATE '2025-01-01'           -- date window in ON\nGROUP BY u.usr;",
'do-leaf-trunc':"SELECT user_id,\n       DATE_TRUNC('month', d)::date AS bucket,\n       COUNT(DISTINCT d) AS n_days\nFROM tbl\nGROUP BY user_id, DATE_TRUNC('month', d)\nHAVING COUNT(DISTINCT d) >= 5;   -- optional per-bucket gate",
'do-leaf-extract':"SELECT EXTRACT(DOW FROM d)::int AS dow, COUNT(*) AS n\nFROM tbl\nGROUP BY EXTRACT(DOW FROM d)\nORDER BY dow;",
'do-leaf-arithmetic':"SELECT id, start_date + term_days AS end_date   -- DATE + INT moves N days\nFROM tbl\nWHERE start_date + term_days <= DATE '2024-02-01';  -- literal cutoff",
'do-leaf-duration':"SELECT id,\n  EXTRACT(EPOCH FROM (end_ts - start_ts)) / 3600 AS hours   -- /86400 for days\nFROM tbl;",
'do-leaf-daycount':"SELECT id, (end_date - start_date) + 1 AS days_inclusive   -- +1 = inclusive\nFROM tbl;",
'rf-antijoin-notexists':"SELECT c.*\nFROM customers c\nWHERE NOT EXISTS (\n  SELECT 1 FROM orders o WHERE o.customer_id = c.id\n);",
'rf-antijoin-notin':"SELECT *\nFROM customers\nWHERE id NOT IN (\n  SELECT customer_id FROM orders WHERE customer_id IS NOT NULL  -- guard NULLs\n);",
'rf-antijoin-leftnull':"SELECT c.*\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id\nWHERE o.customer_id IS NULL;",
}

# worked example per leaf: anchor -> (inCols, inRows, outCols, outRows)
EX={
'gl-leaf-where':(["user","active_days"],[["alice","6"],["bob","3"],["eve","5"]],["user","min_calories"],[["alice","180"],["eve","150"]]),
'gl-leaf-rownumber':(["user","workout","cal"],[["alice","Run","320"],["alice","Yoga","180"],["bob","—","—"]],["user","min_calories","workout"],[["alice","180","Yoga"],["bob","NaN","NULL"]]),
'gl-leaf-distincton':(["user","workout","cal"],[["alice","Run","320"],["alice","Yoga","180"]],["user","workout","cal"],[["alice","Yoga","180"]]),
'gl-leaf-case':(["user","active_days","min(cal)"],[["alice","6","180"],["bob","3","(none)"],["eve","5","150"]],["user","active_days","min_calories"],[["alice","6","180"],["bob","3","NaN"],["eve","5","150"]]),
'gl-leaf-onclause':(["user","workout","flag"],[["alice","Run","true"],["alice","Yoga","false"]],["user","valid_workouts"],[["alice","1"],["bob","0"]]),
'gl-case-around-threshold':(["entity","score","min(val)"],[["a1","85","12"],["a2","40","(none)"]],["entity","best"],[["a1","12"],["a2","NaN"]]),
'gl-case-around-flag':(["entity","is_active","max(val)"],[["a1","true","9"],["a2","false","7"]],["entity","best"],[["a1","9"],["a2","NaN"]]),
'gl-case-inside':(["entity","price"],[["a1","90"],["a1","45"],["a2","(none)"]],["entity","hits"],[["a1","1"],["a2","0"]]),
'dd-leaf-rownumber':(["id","key","created"],[["1","A","Jan1"],["2","A","Jan5"],["3","B","Jan2"]],["id","key (kept)"],[["2","A"],["3","B"]]),
'dd-leaf-selfjoin':(["id","key"],[["1","A"],["2","A"],["3","B"]],["id","key (kept)"],[["1","A"],["3","B"]]),
'dd-leaf-minid':(["id","key"],[["1","A"],["2","A"],["3","B"]],["id","key (kept)"],[["1","A"],["3","B"]]),
'pit-leaf-fill':(["entity","ts","val"],[["x","Dec20","10"],["x","Dec28","12"]],["day","entity","val_as_of"],[["Dec29","x","12"],["Dec30","x","12"]]),
'pit-leaf-default':(["entity"],[["x"],["y"]],["entity","val_as_of"],[["x","12"],["y","0"]]),
'pit-leaf-asof':(["entity","ts","val"],[["x","Dec20","10"],["x","Dec28","12"],["x","Feb01","99"]],["entity","val"],[["x","12"]]),
'up-leaf-aggregate':(["id","q1","q2"],[["1","10","20"],["2","5","NULL"]],["period","total"],[["q1","15"],["q2","20"]]),
'up-leaf-keep':(["id","q1","q2"],[["1","10","NULL"]],["id","period","amt"],[["1","q1","10"],["1","q2","NULL"]]),
'up-leaf-drop':(["id","q1","q2"],[["1","10","NULL"]],["id","period","amt"],[["1","q1","10"]]),
'ej-leaf-selfjoin':(["id","name","manager_id"],[["1","ann","NULL"],["2","bob","1"]],["employee","manager"],[["bob","ann"]]),
'ej-leaf-cross':(["entity / day"],[["x, y"],["d1, d2"]],["entity","day","val"],[["x","d1","5"],["x","d2","0"],["y","d1","0"]]),
'ej-leaf-pergroup':(["key","val"],[["A","10"],["A","20"],["B","5"]],["key","val","grp_avg"],[["A","10","15"],["A","20","15"],["B","5","5"]]),
'ej-leaf-compound':(["id","balance","recent?"],[["101","850","no"],["102","620","YES"],["105","550","none"]],["id","balance","total"],[["101","850","2"],["105","550","0"]]),
'ej-leaf-lookup':(["id","dim_id"],[["1","10"],["2","20"]],["id","label"],[["1","red"],["2","blue"]]),
'sc-leaf-aggregate':(["val"],[["10"],["40"],["25"]],["top_val"],[["40"]]),
'sc-leaf-ratio':(["flag"],[["true"],["false"],["true"],["true"]],["rate"],[["0.75"]]),
'sc-leaf-nth':(["val"],[["40"],["40"],["25"],["10"]],["second_highest"],[["25"]]),
'sc-leaf-top1':(["name","val"],[["a","10"],["b","40"],["c","25"]],["name","val"],[["b","40"]]),
'rp-multi-special':(["key","period","val"],[["A","1","10"],["A","2","14"]],["key","period","delta"],[["A","1","NULL"],["A","2","4"]]),
'rp-multi-topn':(["grp","val"],[["A","9"],["A","7"],["A","3"]],["grp","val","rn"],[["A","9","1"],["A","7","2"]]),
'rp-multi-nth':(["grp","val"],[["A","9"],["A","7"],["A","3"]],["grp","val (rn=2)"],[["A","7"]]),
'rp-multi-top1-by-date':(["grp","ts","val"],[["A","Jan1","5"],["A","Jan9","8"]],["grp","val"],[["A","8"]]),
'rp-multi-top1-by-value':(["grp","val"],[["A","9"],["A","7"]],["grp","val"],[["A","9"]]),
'rf-leaf-pattern':(["name"],[["Ann"],["Bob"],["Amy"]],["name (LIKE 'A%')"],[["Ann"],["Amy"]]),
'rf-leaf-null':(["id","val"],[["1","10"],["2","NULL"]],["id","val"],[["2","NULL"]]),
'rf-leaf-membership':(["id"],[["1"],["2"],["3"]],["id (in other)"],[["2"],["3"]]),
'rf-leaf-antijoin':(["id"],[["1"],["2"],["3"]],["id (not in other)"],[["1"],["3"]]),
'rf-leaf-having':(["key"],[["A"],["A"],["A"],["B"]],["key","n (>=3)"],[["A","3"]]),
'rf-leaf-compare':(["val","status"],[["15","active"],["5","active"],["18","off"]],["val","status"],[["15","active"]]),
'ag-leaf-having':(["key","val"],[["A","60"],["A","60"],["B","30"]],["key","total (>100)"],[["A","120"]]),
'ag-leaf-conditional':(["key","type","val"],[["A","a","10"],["A","b","5"]],["key","a_total","b_total"],[["A","10","5"]]),
'ag-leaf-ratio':(["key","flag"],[["A","true"],["A","false"]],["key","rate"],[["A","0.5"]]),
'ag-leaf-countdistinct':(["key","user"],[["A","u1"],["A","u1"],["A","u2"]],["key","users"],[["A","2"]]),
'ag-leaf-count':(["key"],[["A"],["A"],["B"]],["key","n"],[["A","2"],["B","1"]]),
'ag-leaf-sumavg':(["key","val"],[["A","10"],["A","20"]],["key","total","mean"],[["A","30","15"]]),
'rp-leaf-median':(["key","val"],[["A","1"],["A","3"],["A","5"]],["key","median"],[["A","3"]]),
'rp-leaf-pct-agg':(["key","val"],[["A","1"],["A","5"],["A","9"]],["key","p90"],[["A","8.2"]]),
'rp-leaf-pctrank':(["key","val"],[["A","9"],["A","8"],["A","3"]],["key","val","pr"],[["A","9","0.0"]]),
'rp-leaf-ntile':(["val"],[["1"],["2"],["3"],["4"]],["val","quartile"],[["1","1"],["2","2"],["3","3"],["4","4"]]),
'rp-leaf-rownum':(["key","val"],[["A","9"],["A","7"],["A","3"]],["key","val","rn"],[["A","9","1"],["A","7","2"]]),
'rp-leaf-rank':(["val"],[["9"],["9"],["7"]],["val","rk"],[["9","1"],["9","1"],["7","3"]]),
'rp-leaf-denserank':(["val"],[["9"],["9"],["7"]],["val","rk"],[["9","1"],["9","1"],["7","2"]]),
'un-leaf-labels':(["labels / tbl"],[["a,b,c"],["a,a,c"]],["name","n"],[["a","2"],["b","0"],["c","1"]]),
'un-leaf-reconcile':(["A.id / B.id"],[["1, 2"],["2, 3"]],["id","src"],[["1","only in A"],["3","only in B"]]),
'un-leaf-stack':(["is_new","churned"],[["true","false"],["false","true"]],["metric","count"],[["new","1"],["churned","1"]]),
'tx-leaf-update':(["id","status"],[["1","open"]],["id","status"],[["1","done"]]),
'tx-leaf-coalesce':(["name","nickname"],[["Robert","Bob"],["Amy","NULL"]],["display"],[["Bob"],["Amy"]]),
'tx-leaf-case':(["val"],[["95"],["85"],["70"]],["val","grade"],[["95","A"],["85","B"],["70","C"]]),
'tx-leaf-concat':(["first","last"],[["Ann","Lee"]],["full_name"],[["Ann Lee"]]),
'tx-leaf-substring':(["code"],[["ABC123"]],["prefix","rest"],[["ABC","123"]]),
'tx-leaf-upperlower':(["code","email"],[["ab","A@X.COM"]],["code_up","email_lc"],[["AB","a@x.com"]]),
'tx-leaf-replace':(["phone"],[[" 555-1234 "]],["clean"],[["5551234"]]),
'sess-start':(["user","ts"],[["u1","10:00"],["u1","10:05"],["u1","11:00"]],["user","ts","session_id"],[["u1","10:00","1"],["u1","10:05","1"],["u1","11:00","2"]]),
'tw-tmpl-laglead':(["key","t","val"],[["A","1","10"],["A","2","14"]],["t","val","prev","next"],[["1","10","NULL","14"],["2","14","10","NULL"]]),
'tw-tmpl-firstlast':(["key","t","val"],[["A","1","10"],["A","2","14"],["A","3","9"]],["t","val","first_val"],[["1","10","10"],["2","14","10"],["3","9","10"]]),
'tw-tmpl-pit':(["entity","ts","val"],[["x","Dec20","10"],["x","Dec28","12"]],["entity","val"],[["x","12"]]),
'tw-tmpl-sliding':(["t","val"],[["1","10"],["2","20"],["3","30"]],["t","val","rolling"],[["1","10","10"],["2","20","15"],["3","30","25"]]),
'tw-tmpl-benchmark':(["key","val"],[["A","10"],["A","20"]],["val","vs_group_avg"],[["10","-5"],["20","5"]]),
'tw-tmpl-running':(["t","val"],[["1","10"],["2","20"],["3","5"]],["t","running_total"],[["1","10"],["2","30"],["3","35"]]),
'tw-tmpl-benchmark-frame':(["key","t","val"],[["A","1","10"],["A","2","20"]],["t","group_avg"],[["1","15"],["2","15"]]),
'nb-leaf-matchup':(["home","away","hs","as"],[["A","B","3","1"]],["player","pts"],[["A","3"],["B","1"]]),
'nb-leaf-canon':(["a","b"],[["A","B"],["B","A"]],["p1","p2","n"],[["A","B","2"]]),
'nb-leaf-pool':(["a","b"],[["A","B"],["A","C"]],["id","n"],[["A","2"],["B","1"],["C","1"]]),
'ea-leaf-leftjoin-on':(["entity / tbl.flag"],[["x, y"],["x:true, x:false"]],["entity","n"],[["x","1"],["y","0"]]),
'ea-leaf-membership':(["entity","item"],[["x","X"],["y","X"],["y","Z"]],["entity (has X, no Z)"],[["x"]]),
'ea-leaf-datewin':(["user","signup / order"],[["1","Jan1"],["1","Jan10, Mar1"]],["id","orders_30d"],[["1","1"]]),
'ea-leaf-rate':(["key","converted"],[["A","true"],["A","false"]],["key","conv_rate"],[["A","0.5"]]),
'ea-leaf-filter':(["key","val"],[["A","60"],["A","60"]],["key","total (>100)"],[["A","120"]]),
'ea-leaf-count':(["entity / tbl"],[["x, y"],["x, x"]],["entity","n"],[["x","2"],["y","0"]]),
'ea-leaf-sumavg':(["entity / tbl.val"],[["x, y"],["x:10, x:20"]],["entity","total"],[["x","30"],["y","NULL"]]),
'ml-tmpl-310':(["team","gf","ga"],[["A","2","1"],["A","1","1"]],["team","pts"],[["A","4"]]),
'ml-tmpl-winloss':(["team","gf","ga"],[["A","2","1"],["A","0","1"]],["team","wins","losses"],[["A","1","1"]]),
'ml-tmpl-gfga':(["team","gf","ga"],[["A","2","1"],["A","1","3"]],["team","gf","ga","diff"],[["A","3","4","-1"]]),
'ml-tmpl-sumcol':(["team","points"],[["A","3"],["A","1"]],["team","total"],[["A","4"]]),
'pv-leaf-signed':(["account","type","amt"],[["x","credit","100"],["x","debit","30"]],["account","net"],[["x","70"]]),
'pv-leaf-membership':(["user","item"],[["u","X"],["u","Y"]],["user (X,Y no Z)"],[["u"]]),
'pv-leaf-threshold':(["user","cat","amt"],[["u","a","50"],["u","b","60"]],["user (>=50 each)"],[["u"]]),
'pv-leaf-derived':(["user","weekday"],[["u","Sun"],["u","Sat"],["u","Sun"]],["user","sun","sat"],[["u","2","1"]]),
'pv-leaf-zerofill':(["user","cat","amt"],[["u","a","10"]],["user","a","b"],[["u","10","0"]]),
'pv-leaf-stored':(["user","cat","amt"],[["u","a","10"],["u","b","5"]],["user","a","b"],[["u","10","5"]]),
'sg-leaf-overlap':(["period / span"],[["Q1, Q2"],["Q1..Q2"]],["period","active"],[["Q1","1"],["Q2","1"]]),
'sg-leaf-lateral':(["id","start","end"],[["1","d1","d3"]],["id","day"],[["1","d1"],["1","d2"],["1","d3"]]),
'sg-leaf-labels':(["tiers / val"],[["low 0-9, mid 10-99"],["5, 50"]],["label","n"],[["low","1"],["mid","1"]]),
'sg-leaf-filtered':(["calendar / actuals"],[["d1, d2"],["x:d1"]],["day","entity","n"],[["d1","x","1"],["d2","x","0"]]),
'sg-leaf-databounds':(["day"],[["d2"],["d4"]],["day (spine)"],[["d2"],["d3"],["d4"]]),
'sg-leaf-fullrange':(["entity"],[["x"],["y"]],["day","entity"],[["Jan1","x"],["Jan1","y"],["Jan2","x"]]),
'function-wrapped-scalar':(["id","x"],[["1","4"],["1","6"]],["best_rate(1)"],[["5.0"]]),
'function-wrapped':(["key","val"],[["A","9"],["A","3"]],["id","val"],[["1","9"],["2","3"]]),
'rc-leaf-neighbor-value':(["k","t","val"],[["A","1","10"],["A","2","14"]],["t","val","dir"],[["1","10","NULL"],["2","14","up"]]),
'rc-leaf-gap-delta':(["k","t"],[["A","Jan1"],["A","Jan4"]],["t","gap"],[["Jan1","NULL"],["Jan4","3"]]),
'rc-leaf-fixed-run':(["id","val"],[["1","5"],["2","5"],["3","5"]],["id","val (in a run)"],[["2","5"]]),
'rc-leaf-pair-role':(["key","role","t"],[["A","start","1"],["A","end","5"]],["key","duration"],[["A","4"]]),
'gi-leaf-int':(["id"],[["1"],["2"],["4"]],["grp","min","max"],[["1","1","2"],["2","4","4"]]),
'gi-leaf-entity':(["entity","status","day"],[["x","on","d1"],["x","on","d2"]],["entity","status","min","max"],[["x","on","d1","d2"]]),
'gi-leaf-date-nogap':(["day"],[["d1"],["d2"],["d4"]],["min","max"],[["d1","d2"],["d4","d4"]]),
'gi-leaf-date-gap':(["status","day"],[["on","d1"],["on","d2"],["off","d3"]],["status","min","max"],[["on","d1","d2"],["off","d3","d3"]]),
'ea-leaf-leftjoin-on':(["dept","order_date"],[["A","Jan10"],["A","Jan20"],["B","(none)"]],["dept","q1_count"],[["A","2"],["B","0"]]),
'fj-leaf-status':(["team","status"],[["A","resolved"],["A","open"],["B","(none)"]],["team","resolved"],[["A","1"],["B","0"]]),
'fj-leaf-threshold':(["store","amount"],[["A","150"],["A","80"],["B","(none)"]],["store","big"],[["A","1"],["B","0"]]),
'fj-leaf-bothsides':(["emp","hire","sess_date"],[["Ann","2024","Jan10"],["Bob","2023","Jan15"],["Cara","2024","(none)"]],["emp","q1"],[["Ann","1"],["Cara","0"]]),
'fj-leaf-sumcoalesce':(["cust","status","amt"],[["Amy","completed","100"],["Amy","cancelled","999"],["Ben","(none)","(none)"]],["cust","spend"],[["Amy","100"],["Ben","0"]]),
'fj-leaf-existence':(["usr","order_date"],[["Uma","2024-03"],["Val","2023-12"],["Wes","(none)"]],["usr","ordered_2024"],[["Uma","1"],["Val","0"],["Wes","0"]]),
'do-leaf-trunc':(["user","d"],[["1","Jan10"],["1","Jan20"],["1","Feb03"]],["user","bucket","n_days"],[["1","2024-01-01","2"],["1","2024-02-01","1"]]),
'do-leaf-extract':(["d (weekday)"],[["Sun Jan7"],["Mon Jan8"],["Mon Jan15"]],["dow","n"],[["0","1"],["1","2"]]),
'do-leaf-arithmetic':(["id","start","term"],[["1","Jan01","30"],["2","Feb15","7"]],["id","end_date"],[["1","2024-01-31"]]),
'do-leaf-duration':(["id","start_ts","end_ts"],[["1","09:00","12:00"],["2","Day1 08:00","Day2 08:00"]],["id","hours"],[["1","3.0"],["2","24.0"]]),
'do-leaf-daycount':(["id","start","end"],[["1","Jan01","Jan10"],["2","Mar01","Mar01"]],["id","days_inclusive"],[["1","10"],["2","1"]]),
'rf-antijoin-notexists':(["cust_id","has order?"],[["1","yes"],["2","no"],["3","yes"]],["cust_id (never)"],[["2"]]),
'rf-antijoin-notin':(["cust_id","has order?"],[["1","yes"],["2","no"],["3","yes"]],["cust_id (never)"],[["2"]]),
'rf-antijoin-leftnull':(["cust_id","has order?"],[["1","yes"],["2","no"],["3","yes"]],["cust_id (never)"],[["2"]]),
}
